EAC-4613 Add observe as alternative to then
thousandeyes/thousandeyes-futures pull request #19
Opened 2024-01-29 16:18 UTC by manutzin-te

Different from then(), observe() returns void and will call the continuation on the executor thread. Any exceptions thrown by the continuation will therefore affect the executor's dispatch thread.

It's intended use case is fire-and-forget futures that we still want to .get() to not silently swallow any exceptions.

2024-01-29 16:38 UTC, ggeorgalis requested changes
LGTM! Mostly typos :)

2024-01-29 16:38 UTC, ggeorgalis commented on include/thousandeyes/futures/observe.h
> +//! \brief Observes the input futures and calls the given contionuation function once
Typo: contionuation

2024-01-29 16:38 UTC, ggeorgalis commented on include/thousandeyes/futures/observe.h
> +//! \brief Observes the input futures and calls the given contionuation function once
Typo: contionuation

2024-01-29 16:38 UTC, ggeorgalis commented on include/thousandeyes/futures/observe.h
> +//! \brief Observes the input futures and calls the given contionuation function once
Typo: contionuation

2024-01-29 16:41 UTC, manutzin-te commented on tests/defaultexecutor.cpp
> +                f.get();
I wanted to capture the fact that the exception is propagated into the dispatcher thread. If we're fine with testing only the fact that `observe` calls the continuation, then indeed `EXPECT_THROW` is enough.

2024-01-29 17:08 UTC, jstinson-te approved these changes
LGTM - some minor suggestions.

2024-01-29 17:08 UTC, jstinson-te commented on tests/defaultexecutor.cpp
> +                // is never executed.
If we expect to never get to this code, why not add a `FAIL() << "Should not be executed";` line to incidate the issue to the person running the test?

2024-01-29 17:08 UTC, jstinson-te commented on tests/defaultexecutor.cpp
> +    // This will never become true, as the continuation will rethrow the exception
Can we add a `EXPECT_FALSE(success);` to the end of the test to make this expectation checked?

2024-01-30 10:57 UTC, ggeorgalis commented on tests/defaultexecutor.cpp
> +                f.get();
It's fine to leave as is. Only, it looks more like an integration test than a unit test.

2024-01-30 10:57 UTC, ggeorgalis approved these changes

2024-01-30 11:35 UTC, merged